name: Deploy to production

env:
  DOCKER_IMAGE_NAME: michaeljohn007-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: michaljohn007-ttt-app
  
on:
  pull_request:
    types: [labeled]
    
jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: webpack artifacts
          path: public/
          
  Build-Docker-Image:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    name: Build imag and store in GitHub Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: webpack artifacts
          path: public
          
      - name: create image and store in Packages
        uses: mattdavis0351/actions/docker-gpr@1.3.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          image-name: ${{env.DOCKER_IMAGE_NAME}}
          
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: Build-Docker-Image
    name: Deploy app container to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/michaeljohn007/devops-p9/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}
          
      - name: Azure logout
        run: |
          az logout
